### ISSUE TITLE
Check out postcss-instagram

### ISSUE THREAD

**Issue by himynameisdave** [una/CSSgram#1]
You might wanna check out the [`postcss-instagram`](https://github.com/azat-io/postcss-instagram) plugin for PostCSS for inspiration.

I really like where you're going with this though and great name choice! :smile: :+1:

**Comment by una** [comment]
Oh my gosh I literally made a post CSS project to do the same thing today 😐

**Comment by cybear** [comment]
Keep this repo going! This is much easier to read and learn from than the PostCSS-instagram because that one is in JS.

**Comment by una** [comment]
I think I'm going to do both -- I think postCSS makes for a better workflow and makes sense, but this one has a lower barrier-to-entry and is easier to pull from individually. 

The implementation of the one @himynameisdave is a little different than what I started with PostCSS as well, so I may as well keep hacking on it as well

So :) things to come

**Comment by himynameisdave** [comment]
@una looking forward to it, I feel like people will love this and also CSS filters are :ok_hand: :smile:
