### ISSUE TITLE
A few of the example filters don't seem to work at http://una.im/CSSgram/

### ISSUE THREAD

**Issue by kodie** [una/CSSgram#139]
![screenshot 2015-11-27 10 16 01](https://cloud.githubusercontent.com/assets/603949/11445222/f1f678d8-94ef-11e5-86f6-018bc8ff40c0.png)

Using Chrome Version 46.0.2490.86 m on Windows 10.

Just thought I'd let you know!

Thanks!

**Comment by shelune** [comment]
That's really weird O.o I have the same version of Chrome and Windows and they all work for me

**Comment by kodie** [comment]
hmm I'm not sure, I disabled all of my plugins and tried it in incognito mode and the Earlybird, Mayfair, and Brooklyn filters don't show the image through the filter for some reason.

**Comment by una** [comment]
Interesting. Thanks for pointing that out. I will take a look -- it seems like specific blend modes on ::after elements aren't working

**Comment by una** [comment]
Sorted: these all use the `overlay` blend mode

**Comment by una** [comment]
Chrome has notable bugs with certain blend modes in version 46 (see [caniuse](http://caniuse.com/#feat=css-backgroundblendmode))
