### ISSUE TITLE
Willow demo broken in Safari

### ISSUE THREAD

**Issue by mislav** [una/CSSgram#149]
Willow doesn't display in Safari (there is only a grayed square) until hovered over, when the normal unprocessed image appears.

[Screenshot](https://twitter.com/mislav/status/679356015285026818)

**Comment by PaulCWoods** [comment]
From Can I Use
Partial in Safari refers to not supporting the hue, saturation, color, and luminosity blend modes.
That would explain the solid grey colour

**Comment by tomByrer** [comment]
I don't see that comment in Can I Use anymore; have a live demo please?

**Comment by una** [comment]
Closing due to this showing browser capabilities
