### ISSUE TITLE
CDN down?

### ISSUE THREAD

**Issue by nicgutierrez** [una/CSSgram#170]
Hi

It seems that the CDN is currently down? I'm getting 502 Bad Gateway -> https://cssgram-cssgram.netdna-ssl.com/cssgram.min.css

Thanks :)

**Comment by una** [comment]
Seems to be working for me -- try again?

**Comment by JackPu** [comment]
it works for me too.

**Comment by sandmanx** [comment]
I think we can close this issue :)
