### ISSUE TITLE
Filter: Nashville

### ISSUE THREAD

**Issue by una** [una/CSSgram#18]

**Comment by dbox** [comment]
Great project :) 

I'm going to be impressed if you're able to recreate Nashville with just css filters. The key is adjusting shadow levels to be blue while simultaneously adjusting highlights to be cream.

I tackled a lot of these a few years ago as photoshop actions:
http://dbox.tumblr.com/post/5426249009/instagram-filters-as-photoshop-actions

**Comment by una** [comment]
Thanks for the tip! And great article :)

**Comment by una** [comment]
Resolved via #100

**Comment by dbox** [comment]
nice!
