### ISSUE TITLE
Wanting to Contribute

### ISSUE THREAD

**Issue by cedricium** [una/CSSgram#229]
So I have gone ahead and created/replicated one of Instagram's filter, but I have two things I need help with before creating a PR for my filter. 
1. I noticed some filters have a "`filterName::after {...`" attribute and I was wondering whether or not that is necessary for every filter. 
2. Also, as the creator of one filter, am I also responsible for the creation of the SCSS as well? I only ask because I have no experience with SCSS and could use some help with it. 

Please let me know, I am very eager and willing to contribute to such an awesome project!

**Comment by una** [comment]
Hi!

1. Yes, thats how the filters work -- on pseudo elements
2. Yes, filters are written in SCSS :) it's a great opportunity to learn and get a bit better at it!
