### ISSUE TITLE
Separate dev build

### ISSUE THREAD

**Issue by Praseetha-KR** [una/CSSgram#239]
Hi @una,

Currently, **compiled files needs to be removed manually** whenever:

- pushing to github (to keep the PRs clean)
- switching between branches

One approach to solve this problem would be to **keep a separate folder for compiled files in local development**, and there will be 2 gulp tasks:

1. `gulp` - *can be run on any branch*
   -  This generates a `.dev` folder, which serves as local dev server root
   -     `scss/twig` compiled files will be generated inside this folder.
   -     `test/`, `img/`, `filters.json` will also be copied to this
   -     This folder will be added in `.gitignore` 
so none of the compiled files appear in `git status`. PRs will contain only changed files.

2. `gulp build` - *run only in master*
This does compilations and places the generated files in the same place as current directory structure.

What do you think?

![devbuild](https://cloud.githubusercontent.com/assets/1054350/19330009/5c38b1e2-90f9-11e6-9ca0-91072863fa10.jpg)

**Comment by una** [comment]
This is definitely a good idea :) Thanks for the suggestion/diagram

**Comment by Praseetha-KR** [comment]
Fixed in #242
