### ISSUE TITLE
Site - cacti.jpg fails to load on the page.

### ISSUE THREAD

**Issue by 526avijitgupta** [una/CSSgram#26]
The cacti image fails to load on the site, showing a `404 - Not Found`  error in the Network Requests.
![screenshot from 2015-10-27 19 50 03](https://cloud.githubusercontent.com/assets/7583815/10760788/59864ad8-7ce4-11e5-873a-53fd3c755e36.png)

**Comment by una** [comment]
Hi, can you tell me if you're still getting this error? 

I updated the file name from *cacti.jpg* to *cacti.JPG* a little while ago but it seems like you didn't get the update. I pushed new changes to the site, so it may have fixed this.

Thanks for pointing it out! Please let me know!

**Comment by 526avijitgupta** [comment]
Hi @una, cacti.jpg (old reference) still remains [here](https://github.com/una/CSSgram/blob/c0b9347c89ac91c8f2f38996c7c3766fc4282de7/site/index.html#L32) in the latest code which causes the error. I am closing this pull request and creating an updated one for the fix.

**Comment by una** [comment]
hmm. The lowercase .jpg is the reference I intended...

It was the image file which was incorrect and was also updated yesterday, which is why I ask if you are still getting an errror?
