### ISSUE TITLE
Add All Filters to Test Page

### ISSUE THREAD

**Issue by una** [una/CSSgram#96]
The [test page](http://una.im/CSSgram/test/) is missing a few filters. Let's document which ones exist and which ones are in need of getting added.

**Comment by m1** [comment]
Which filters do you know of that are missing? Will try and get them up but I'm pretty sure I did all the filters that were on the version of instagram (android emulator) I was using.

**Comment by una** [comment]
ooh! There are likely more in the iOS version. Check out the README for the full list (i.e. Moon and Clarendon)

**Comment by m1** [comment]
Okay I found the issue, for some reason in the android emulator some filters are toggled off so a big update of the test page will come soon with around 15 more filters.

**Comment by m1** [comment]
Also since the new filters add ~75 new images, plus this with the current filters it's around 195 images on a single page -- maybe we should think about having a test page for each filter (this could be done programmatically via gulp) or having a accordion à la the one in bootstrap. What do you think @una ?

**Comment by una** [comment]
@m1 Good point --  we could have a single page w/a left-side menu that will AJAX the test images in upon request? That would only need a single page still, and we can use HTML push-state for linking

**Comment by m1** [comment]
Sounds brill, I'll do the new filters first then get on with the new test stuff and clear up https://github.com/una/CSSgram/issues/109 in the process.

**Comment by una** [comment]
Rockstar :guitar:
